
#' Read in cleaned Black Knight+Spatial data for Montgomery County
#'
#'
#'
#' @param rmd indicates whether or not function is being called from an 
#' Rmd document or not. Default is set to TRUE.
#'
#' @return dataframe of black knight data for Montgomery county, with all variables that were created in the clean and preclean phase.
#' @export
#'
#' @examples jur <- read_jurisdiction("arlington", rmd = TRUE)
read_montgomery <- function(rmd = TRUE) {
  
  filename <- paste0("L:/Libraries/RegHsg/Data/", filepath,
                     "/", "cleaned-", filepath, "-data.csv")

  if (!file.exists(filename)) {
    stop("cleaned data not found in Data directory")
  } else {
    
    read_csv(filename,
             col_types = cols(county_fips = col_character(),
                              county_name = col_character(),
                              assessorsparcelnumberapnpin = col_character(),
                              propaddress = col_character(),
                              propcity = col_character(),
                              propstate = col_character(),
                              propzip = col_integer(),
                              propunitno = col_integer(),
                              prophouseno = col_character(),
                              propstreetname = col_character(),
                              propstreetsuffix = col_character(),
                              tract = col_double(),
                              owneroccupiedresidential = col_character(),
                              countylandusedescription = col_character(),
                              zoning = col_character(),
                              buildingarea = col_double(),
                              noofbuildings = col_character(),
                              noofstories = col_character(),
                              numberofunits = col_integer(),
                              yearbuilt = col_integer(),
                              lotsize_acres = col_double(),
                              lotsize_sf = col_double(),
                              address_type = col_character(),
                              category = col_character(),
                              category_detail = col_character(),
                              residential = col_integer(),
                              building_type = col_character(),
                              totalassessedvalue = col_double(),
                              assessedlandvalue = col_double(),
                              assessedimprovementvalue = col_double(),
                              parcel_address = col_character(),
                              lsmax = col_character(),
                              vac2 = col_character(),
                              vacant_flag = col_character(),
                              missing_coord = col_integer(),
                              validgeo.x = col_integer(),
                              OBJECTID.x = col_double(),
                              ACCT = col_character(),
                              STATUS = col_character(),
                              TOWN_CODE = col_integer(),
                              DISTRICT = col_character(),
                              SUBDIVISIO = col_character(),
                              SORT_KEY = col_character(),
                              SDAT_AREA = col_double(),
                              ACRE_OR_SQ = col_character(),
                              LIBER = col_character(),
                              FOLIO = col_character(),
                              LOT = col_character(),
                              BLOCK = col_character(),
                              TAX_CLASS = col_integer(),
                              ASSMT_DATE = col_integer(),
                              LAND_ASSMT = col_double(),
                              PREF_ASSMT = col_double(),
                              IMPROV_ASS = col_double(),
                              EXEMPT_COD = col_character(),
                              GRID = col_character(),
                              PARCEL_NO = col_character(),
                              SUBPARCEL = col_character(),
                              PROPERTY_C = col_character(),
                              LANDUSE_CO = col_integer(),
                              LU_CATEGOR = col_character(),
                              AZ_CODE = col_character(),
                              AZCODE_NAM = col_character(),
                              DWELLINGCO = col_character(),
                              DWELLSTORY = col_character(),
                              PUBLICUSE_ = col_character(),
                              TRANSFER_D = col_date(format = ""),
                              SALES_PRIC = col_double(),
                              LEGAL_DESC = col_character(),
                              PREMISE_AD = col_integer(),
                              PREMISE__1 = col_character(),
                              PREMISE__2 = col_character(),
                              PREMISE__3 = col_character(),
                              PREMISE__4 = col_character(),
                              PREMISE__5 = col_integer(),
                              PREMISE__6 = col_integer(),
                              CONDO_UNIT = col_character(),
                              OWNERS_OCC = col_character(),
                              OWNERS_NAM = col_character(),
                              OWNERS_N_1 = col_character(),
                              OWNERS_ADD = col_character(),
                              OWNERS_A_1 = col_character(),
                              OWNERS_A_2 = col_character(),
                              OWNERS_CIT = col_character(),
                              OWNERS_STA = col_character(),
                              OWNERS_ZIP = col_integer(),
                              OWNERS_Z_1 = col_integer(),
                              ZONE_.x = col_character(),
                              GR_FLR_ARE = col_double(),
                              NO_STORIES = col_integer(),
                              NO_DWELLIN = col_integer(),
                              DWELLING_T = col_character(),
                              DWELLINGTY = col_character(),
                              YEAR_BUILT = col_integer(),
                              LOT_WIDTH = col_integer(),
                              LOT_DEPTH = col_integer(),
                              DWELLING_G = col_integer(),
                              DWELLING_C = col_character(),
                              DWELLING_S = col_character(),
                              DWELLING_1 = col_integer(),
                              UTILITIES_ = col_integer(),
                              UTILITIES1 = col_integer(),
                              LOCATION_W = col_integer(),
                              STREET_PAV = col_integer(),
                              STREET_UNP = col_integer(),
                              COMMER_IND = col_character(),
                              HISTORICAL = col_integer(),
                              PUBLIC_USE = col_double(),
                              ACTIVITY_D = col_date(format = ""),
                              CREATION_D = col_integer(),
                              DELETION_D = col_character(),
                              RAZED = col_character(),
                              PARENT_TAX = col_character(),
                              MULTIPAREN = col_integer(),
                              RAZED_DATE = col_character(),
                              OUTLOT = col_character(),
                              ASSESSCYL = col_integer(),
                              CONDOFLR = col_integer(),
                              TAX_ZONE = col_character(),
                              LOAD_DATE = col_date(format = ""),
                              XSTATECO = col_double(),
                              YSTATECO = col_double(),
                              GEOMETHD = col_character(),
                              TAZ_1999 = col_integer(),
                              TAZ_2009 = col_integer(),
                              CDISTRICT = col_integer(),
                              PLANNING = col_integer(),
                              POLICY = col_character(),
                              MASTER_PLA = col_character(),
                              BASEMAP = col_character(),
                              TAXMAP = col_character(),
                              TAZ_1970 = col_integer(),
                              POLICY_AGP = col_character(),
                              CBPTEAM = col_integer(),
                              WATRSHED = col_character(),
                              MUNICIP = col_character(),
                              CLERK_PLAT = col_character(),
                              RECORD_PLA = col_character(),
                              PLAT_LINK = col_character(),
                              BING3D = col_character(),
                              STREETVIEW = col_character(),
                              RES_DWELLU = col_integer(),
                              NONRES_DWE = col_integer(),
                              PARKING_UN = col_integer(),
                              SQFT_RESID = col_integer(),
                              SQFT_OFFIC = col_integer(),
                              SQFT_RETAI = col_integer(),
                              SQFT_INDUS = col_double(),
                              SQFT_OTHER = col_double(),
                              LAND_ASS_1 = col_double(),
                              IMPROV_A_1 = col_double(),
                              LAND_ASS_2 = col_double(),
                              IMPROV_A_2 = col_integer(),
                              SQFT_PKG = col_integer(),
                              SHAPE_AREA.x = col_double(),
                              SHAPE_LEN.x = col_double(),
                              validgeo.y = col_integer(),
                              arc_lotsize_sf = col_double(),
                              OBJECTID.y = col_integer(),
                              GISADMIN_Z = col_integer(),
                              ZONE_.y = col_character(),
                              CODE = col_character(),
                              PERIMETER = col_integer(),
                              ACRES = col_double(),
                              ZONE1 = col_character(),
                              ZONING_ID = col_integer(),
                              BEGINDATE = col_date(format = ""),
                              BEGINREASO = col_character(),
                              BEGINPLANN = col_character(),
                              ENDDATE = col_character(),
                              ENDREASON = col_character(),
                              ENDPLANNER = col_character(),
                              LONGZONE = col_character(),
                              SHAPE_AREA.y = col_double(),
                              SHAPE_LEN.y = col_double(),
                              validgeo = col_integer(),
                              arc_zoning = col_character()
             ))
  }
}









