
read_bk <- function(datafile) {
    
  # read raw data
    cog_assessment <- read_csv(paste0("L:/Libraries/RegHsg/Raw/", datafile),
                               col_types = 
                                 cols(fipscodestatecounty = col_character(),
                                      bkfsinternalpid = col_integer(),
                                      assessorsparcelnumberapnpin = col_character(),
                                      duplicateapn = col_character(),
                                      propertyaddresssourceflag = col_character(),
                                      propertyfullstreetaddress = col_character(),
                                      propertycityname = col_character(),
                                      propertystate = col_character(),
                                      propertyzipcode = col_character(),
                                      propertyzip4 = col_character(),
                                      propertyunittype = col_character(),
                                      propertyunitnumber = col_character(),
                                      propertyhousenumber = col_character(),
                                      propertystreetdirectionleft = col_character(),
                                      propertystreetname = col_character(),
                                      propertystreetsuffix = col_character(),
                                      propertystreetdirectionright = col_character(),
                                      propertyaddresscarrierroute = col_character(),
                                      propertyaddresslatitiude = col_number(),
                                      propertyaddresslongitude = col_number(),
                                      propertyaddresscensustract = col_character(),
                                      assesseeownername = col_character(),
                                      assesseeownervestingcode = col_character(),
                                      taxaccountnumber = col_character(),
                                      mailcareofname = col_character(),
                                      assesseemailfullstreetaddress = col_character(),
                                      assesseemailcityname = col_character(),
                                      assesseemailstatecode = col_character(),
                                      assesseemailzipcode = col_character(),
                                      assesseemailzip4 = col_character(),
                                      assesseemailunittype = col_character(),
                                      assesseemailunitnumber = col_character(),
                                      owneroccupiedresidential = col_character(),
                                      assessedlandvalue = col_integer(),
                                      assessedimprovementvalue = col_integer(),
                                      totalassessedvalue = col_integer(),
                                      assessmentyear = col_character(),
                                      californiahomeownersexemption = col_character(),
                                      taxexemptioncodes = col_character(),
                                      taxratecodearea = col_character(),
                                      recordersdocumentnumberfromassessment = col_character(),
                                      recordersbooknumberfromassessment = col_character(),
                                      recorderspagenumberfromassessment = col_character(),
                                      recordingdatefromassessment = col_character(),
                                      documenttypefromassessmentcountydescription = col_character(),
                                      salespricefromassessment = col_integer(),
                                      salespricecodefromassessment = col_character(),
                                      priorsaledate = col_character(),
                                      priorsalesprice = col_integer(),
                                      priorsalespricecode = col_character(),
                                      taxsource = col_character(),
                                      taxamount = col_number(),
                                      taxyear = col_character(),
                                      taxdelinquentyear = col_character(),
                                      legallotnumber = col_character(),
                                      legallandlot = col_character(),
                                      legalblock = col_character(),
                                      legalsection = col_character(),
                                      legaldistrict = col_character(),
                                      legalunit = col_character(),
                                      legalcitytownshipmunicipality = col_character(),
                                      legalsubdivisionname = col_character(),
                                      legalphasenumber = col_character(),
                                      legaltractnumber = col_character(),
                                      legalsectiontownshiprangemeridian = col_character(),
                                      legalassessorsmapref = col_character(),
                                      standardizedlandusecode = col_character(),
                                      countylandusedescription = col_character(),
                                      countylandusecode = col_character(),
                                      zoning = col_character(),
                                      lotsizeorarea = col_number(),
                                      lotsizeareaunit = col_character(),
                                      originallotsizeorarea = col_character(),
                                      buildingarea = col_integer(),
                                      mainbuildingareaindicator = col_character(),
                                      yearbuilt = col_character(),
                                      noofbuildings = col_integer(),
                                      noofstories = col_character(),
                                      totalnumberofrooms = col_character(),
                                      numberofunits = col_integer(),
                                      numberofbedrooms = col_integer(),
                                      numberofbaths = col_integer(),
                                      numberofpartialbaths = col_integer(),
                                      garagetypeparking = col_character(),
                                      garageparkingofcars = col_integer(),
                                      pool = col_character(),
                                      marketvalueland = col_integer(),
                                      marketvalueimprovement = col_integer(),
                                      totalmarketvalue = col_integer(),
                                      marketvalueyear = col_character(),
                                      buildingclass = col_character(),
                                      style = col_character(),
                                      typeconstruction = col_character(),
                                      exteriorwalls = col_character(),
                                      foundation = col_character(),
                                      roofcover = col_character(),
                                      heating = col_character(),
                                      airconditioning = col_character(),
                                      elevator = col_character(),
                                      fireplace = col_character(),
                                      basement = col_character(),
                                      currentownermailstreetaddress = col_character(),
                                      currentownermailingcity = col_character(),
                                      currentownermailingstate = col_character(),
                                      currentownermailingzip = col_character(),
                                      currentownermailingzip4 = col_character(),
                                      currentownerunittype = col_character(),
                                      currentownerunitnumber = col_character(),
                                      currentownermailcareofname = col_character(),
                                      assessmentsourcefiledatetapecut = col_character(),
                                      latestsalerecordingdate = col_character(),
                                      latestsalebooknumber = col_character(),
                                      latestsalepagenumber = col_character(),
                                      latestsaledocumentnumber = col_character(),
                                      latestsaledocumenttypecode = col_character(),
                                      latestsaleprice = col_character(),
                                      latestsalepricecode = col_character(),
                                      priorsalerecordingdate = col_character(),
                                      priorsalebooknumber = col_character(),
                                      priorsalepagenumber = col_character(),
                                      priorsaledocumentnumber = col_character(),
                                      priorsaledocumenttypecode = col_character(),
                                      priorsaleprice = col_character(),
                                      priorsalepricecode = col_character(),
                                      latestvalidrecordingdate = col_character(),
                                      latestvalidbooknumber = col_character(),
                                      latestvalidpagenumber = col_character(),
                                      latestvaliddocumentnumber = col_character(),
                                      latestvaliddocumenttypecode = col_character(),
                                      latestvalidprice = col_character(),
                                      latestvalidpricecode = col_character(),
                                      priorvalidrecordingdate = col_character(),
                                      priorvalidbooknumber = col_character(),
                                      priorvalidpagenumber = col_character(),
                                      priorvaliddocumentnumber = col_character(),
                                      priorvaliddocumenttypecode = col_character(),
                                      priorvalidprice = col_character(),
                                      priorvalidpricecode = col_character(),
                                      assesseeownernameindicator = col_character(),
                                      X2ndassesseeownernameindicator = col_character(),
                                      mailcareofnameindicator = col_character(),
                                      assesseeownernametype = col_character(),
                                      X2ndassesseeownernametype = col_character(),
                                      altoldapnindicator = col_character(),
                                      certificationdate = col_character(),
                                      lotsizesquarefeet = col_integer(),
                                      buildingquality = col_character(),
                                      floorcover = col_character(),
                                      ofplumbingfixtures = col_character(),
                                      buildingarea1 = col_integer(),
                                      buildingarea1indicator = col_character(),
                                      buildingarea2 = col_integer(),
                                      buildingarea2indicator = col_character(),
                                      buildingarea3 = col_integer(),
                                      buildingarea3indicator = col_character(),
                                      buildingarea4 = col_integer(),
                                      buildingarea4indicator = col_character(),
                                      buildingarea5 = col_integer(),
                                      buildingarea5indicator = col_character(),
                                      buildingarea6 = col_integer(),
                                      buildingarea6indicator = col_character(),
                                      buildingarea7 = col_integer(),
                                      buildingarea7indicator = col_character(),
                                      effectiveyearbuilt = col_character(),
                                      heatingfueltype = col_character(),
                                      airconditioningtype = col_character(),
                                      lotsizeacres = col_number(),
                                      mortgagelendername = col_character(),
                                      interiorwalls = col_character(),
                                      schooltaxdistrict1 = col_character(),
                                      schooltaxdistrict1indicator = col_character(),
                                      schooltaxdistrict2 = col_character(),
                                      schooltaxdistrict2indicator = col_character(),
                                      schooltaxdistrict3 = col_character(),
                                      schooltaxdistrict3indicatorseebelowforvalues = col_character(),
                                      siteinfluence = col_character(),
                                      amenitiesseeamenities2field190 = col_character(),
                                      otherimprbuildingindicator1 = col_character(),
                                      otherimprbuildingindicator2 = col_character(),
                                      otherimprbuildingindicator3 = col_character(),
                                      otherimprbuildingindicator4 = col_character(),
                                      neighborhoodcode = col_character(),
                                      condoprojectbldgname = col_character(),
                                      otherimprbuildingindicator5 = col_character(),
                                      amenities2seefield182 = col_character(),
                                      otherimprbuildingarea1 = col_character(),
                                      otherimprbuildingarea2 = col_character(),
                                      otherimprbuildingarea3 = col_character(),
                                      otherimprbuildingarea4 = col_character(),
                                      otherimprbuildingarea5 = col_character(),
                                      otherrooms = col_character(),
                                      extrafeatures1area = col_character(),
                                      extrafeatures1indicator = col_character(),
                                      topography = col_character(),
                                      rooftype = col_character(),
                                      extrafeatures2area = col_character(),
                                      extrafeatures2indicator = col_character(),
                                      extrafeatures3area = col_character(),
                                      extrafeatures3indicator = col_character(),
                                      extrafeatures4area = col_character(),
                                      extrafeatures4indicator = col_character(),
                                      oldapn = col_character(),
                                      buildingcondition = col_character(),
                                      lotsizefrontagefeet = col_character(),
                                      lotsizedepthfeet = col_character(),
                                      commentssummaryofbuildingcardsdrrecords = col_character(),
                                      water = col_character(),
                                      sewer = col_character(),
                                      matchcodefromgeostan = col_character(),
                                      locationcodefromgeostan = col_character(),
                                      rawpropertyhousenumber = col_character(),
                                      rawpropertyhousealpha = col_character(),
                                      rawpropertystreetdirectionleft = col_character(),
                                      rawpropertystreetsuffix = col_character(),
                                      rawpropertystreetdirectionright = col_character(),
                                      rawpropertyunitnumber = col_character(),
                                      rawpropertycityname = col_character(),
                                      rawpropertystate = col_character(),
                                      rawpropertyzipcode = col_character(),
                                      rawpropertyzip4 = col_character(),
                                      rawmailinghousenumber = col_character(),
                                      rawmailinghousealpha = col_character(),
                                      rawmailingstreetdirectionleft = col_character(),
                                      rawmailingstreetname = col_character(),
                                      rawmailingstreetsuffix = col_character(),
                                      rawmailingstreetdirectionright = col_character(),
                                      rawmailingunitnumber = col_character(),
                                      rawmailingcityname = col_character(),
                                      rawmailingstate = col_character(),
                                      rawmailingzipcode = col_character(),
                                      rawmailingzip4 = col_character(),
                                      edition = col_character(),
                                      owner1firstname = col_character(),
                                      owner1middlename = col_character(),
                                      owner1lastname = col_character(),
                                      owner2firstname = col_character(),
                                      owner2middlename = col_character(),
                                      parsedownersourcecode = col_character()
                                 ))
                      
    
  # add county names
    county_names <- tibble(
      county_fips = as.character(c(11001, 24017, 24021, 24031, 24033, 
                                   51013, 51059, 51107, 51153, 51510, 
                                   51600, 51610, 51683, 51685)),
      county_name = c("District of Columbia", "Charles County",
                      "Frederick County", "Montgomery County",
                      "Prince George's County", "Arlington County",
                      "Fairfax County", "Loudoun County",
                      "Prince William County", "Alexandria city",
                      "Fairfax city", "Falls Church city",
                      "Manassas city", "Manassas Park city")
      )
    
    cog_assessment <- cog_assessment %>% 
      rename(county_fips = fipscodestatecounty) %>% 
      left_join(county_names, by = "county_fips") %>% 
      select(county_fips, county_name, everything())
    
  # add land use codes
    codes <- read_csv(
      "Doc/assessment_landuse.csv",
      col_names = c("standardizedlandusecode", "codedescription"),
      col_types = cols(standardizedlandusecode = col_character(),
                       codedescription = col_character())
      )
    
    cog_assessment <- cog_assessment %>% 
      left_join(codes, by = "standardizedlandusecode")

  # return dataset  
    cog_assessment
}

read_bk_rmd <- function(datafile) {
  
  # read raw data
  cog_assessment <- read_csv(paste0("L:/Libraries/RegHsg/Raw/", datafile),
                             col_types = 
                               cols(fipscodestatecounty = col_character(),
                                    bkfsinternalpid = col_integer(),
                                    assessorsparcelnumberapnpin = col_character(),
                                    duplicateapn = col_character(),
                                    propertyaddresssourceflag = col_character(),
                                    propertyfullstreetaddress = col_character(),
                                    propertycityname = col_character(),
                                    propertystate = col_character(),
                                    propertyzipcode = col_character(),
                                    propertyzip4 = col_character(),
                                    propertyunittype = col_character(),
                                    propertyunitnumber = col_character(),
                                    propertyhousenumber = col_character(),
                                    propertystreetdirectionleft = col_character(),
                                    propertystreetname = col_character(),
                                    propertystreetsuffix = col_character(),
                                    propertystreetdirectionright = col_character(),
                                    propertyaddresscarrierroute = col_character(),
                                    propertyaddresslatitiude = col_number(),
                                    propertyaddresslongitude = col_number(),
                                    propertyaddresscensustract = col_character(),
                                    assesseeownername = col_character(),
                                    assesseeownervestingcode = col_character(),
                                    taxaccountnumber = col_character(),
                                    mailcareofname = col_character(),
                                    assesseemailfullstreetaddress = col_character(),
                                    assesseemailcityname = col_character(),
                                    assesseemailstatecode = col_character(),
                                    assesseemailzipcode = col_character(),
                                    assesseemailzip4 = col_character(),
                                    assesseemailunittype = col_character(),
                                    assesseemailunitnumber = col_character(),
                                    owneroccupiedresidential = col_character(),
                                    assessedlandvalue = col_integer(),
                                    assessedimprovementvalue = col_integer(),
                                    totalassessedvalue = col_integer(),
                                    assessmentyear = col_character(),
                                    californiahomeownersexemption = col_character(),
                                    taxexemptioncodes = col_character(),
                                    taxratecodearea = col_character(),
                                    recordersdocumentnumberfromassessment = col_character(),
                                    recordersbooknumberfromassessment = col_character(),
                                    recorderspagenumberfromassessment = col_character(),
                                    recordingdatefromassessment = col_character(),
                                    documenttypefromassessmentcountydescription = col_character(),
                                    salespricefromassessment = col_integer(),
                                    salespricecodefromassessment = col_character(),
                                    priorsaledate = col_character(),
                                    priorsalesprice = col_integer(),
                                    priorsalespricecode = col_character(),
                                    taxsource = col_character(),
                                    taxamount = col_number(),
                                    taxyear = col_character(),
                                    taxdelinquentyear = col_character(),
                                    legallotnumber = col_character(),
                                    legallandlot = col_character(),
                                    legalblock = col_character(),
                                    legalsection = col_character(),
                                    legaldistrict = col_character(),
                                    legalunit = col_character(),
                                    legalcitytownshipmunicipality = col_character(),
                                    legalsubdivisionname = col_character(),
                                    legalphasenumber = col_character(),
                                    legaltractnumber = col_character(),
                                    legalsectiontownshiprangemeridian = col_character(),
                                    legalassessorsmapref = col_character(),
                                    standardizedlandusecode = col_character(),
                                    countylandusedescription = col_character(),
                                    countylandusecode = col_character(),
                                    zoning = col_character(),
                                    lotsizeorarea = col_number(),
                                    lotsizeareaunit = col_character(),
                                    originallotsizeorarea = col_character(),
                                    buildingarea = col_integer(),
                                    mainbuildingareaindicator = col_character(),
                                    yearbuilt = col_character(),
                                    noofbuildings = col_integer(),
                                    noofstories = col_character(),
                                    totalnumberofrooms = col_character(),
                                    numberofunits = col_integer(),
                                    numberofbedrooms = col_integer(),
                                    numberofbaths = col_integer(),
                                    numberofpartialbaths = col_integer(),
                                    garagetypeparking = col_character(),
                                    garageparkingofcars = col_integer(),
                                    pool = col_character(),
                                    marketvalueland = col_integer(),
                                    marketvalueimprovement = col_integer(),
                                    totalmarketvalue = col_integer(),
                                    marketvalueyear = col_character(),
                                    buildingclass = col_character(),
                                    style = col_character(),
                                    typeconstruction = col_character(),
                                    exteriorwalls = col_character(),
                                    foundation = col_character(),
                                    roofcover = col_character(),
                                    heating = col_character(),
                                    airconditioning = col_character(),
                                    elevator = col_character(),
                                    fireplace = col_character(),
                                    basement = col_character(),
                                    currentownermailstreetaddress = col_character(),
                                    currentownermailingcity = col_character(),
                                    currentownermailingstate = col_character(),
                                    currentownermailingzip = col_character(),
                                    currentownermailingzip4 = col_character(),
                                    currentownerunittype = col_character(),
                                    currentownerunitnumber = col_character(),
                                    currentownermailcareofname = col_character(),
                                    assessmentsourcefiledatetapecut = col_character(),
                                    latestsalerecordingdate = col_character(),
                                    latestsalebooknumber = col_character(),
                                    latestsalepagenumber = col_character(),
                                    latestsaledocumentnumber = col_character(),
                                    latestsaledocumenttypecode = col_character(),
                                    latestsaleprice = col_character(),
                                    latestsalepricecode = col_character(),
                                    priorsalerecordingdate = col_character(),
                                    priorsalebooknumber = col_character(),
                                    priorsalepagenumber = col_character(),
                                    priorsaledocumentnumber = col_character(),
                                    priorsaledocumenttypecode = col_character(),
                                    priorsaleprice = col_character(),
                                    priorsalepricecode = col_character(),
                                    latestvalidrecordingdate = col_character(),
                                    latestvalidbooknumber = col_character(),
                                    latestvalidpagenumber = col_character(),
                                    latestvaliddocumentnumber = col_character(),
                                    latestvaliddocumenttypecode = col_character(),
                                    latestvalidprice = col_character(),
                                    latestvalidpricecode = col_character(),
                                    priorvalidrecordingdate = col_character(),
                                    priorvalidbooknumber = col_character(),
                                    priorvalidpagenumber = col_character(),
                                    priorvaliddocumentnumber = col_character(),
                                    priorvaliddocumenttypecode = col_character(),
                                    priorvalidprice = col_character(),
                                    priorvalidpricecode = col_character(),
                                    assesseeownernameindicator = col_character(),
                                    X2ndassesseeownernameindicator = col_character(),
                                    mailcareofnameindicator = col_character(),
                                    assesseeownernametype = col_character(),
                                    X2ndassesseeownernametype = col_character(),
                                    altoldapnindicator = col_character(),
                                    certificationdate = col_character(),
                                    lotsizesquarefeet = col_integer(),
                                    buildingquality = col_character(),
                                    floorcover = col_character(),
                                    ofplumbingfixtures = col_character(),
                                    buildingarea1 = col_integer(),
                                    buildingarea1indicator = col_character(),
                                    buildingarea2 = col_integer(),
                                    buildingarea2indicator = col_character(),
                                    buildingarea3 = col_integer(),
                                    buildingarea3indicator = col_character(),
                                    buildingarea4 = col_integer(),
                                    buildingarea4indicator = col_character(),
                                    buildingarea5 = col_integer(),
                                    buildingarea5indicator = col_character(),
                                    buildingarea6 = col_integer(),
                                    buildingarea6indicator = col_character(),
                                    buildingarea7 = col_integer(),
                                    buildingarea7indicator = col_character(),
                                    effectiveyearbuilt = col_character(),
                                    heatingfueltype = col_character(),
                                    airconditioningtype = col_character(),
                                    lotsizeacres = col_number(),
                                    mortgagelendername = col_character(),
                                    interiorwalls = col_character(),
                                    schooltaxdistrict1 = col_character(),
                                    schooltaxdistrict1indicator = col_character(),
                                    schooltaxdistrict2 = col_character(),
                                    schooltaxdistrict2indicator = col_character(),
                                    schooltaxdistrict3 = col_character(),
                                    schooltaxdistrict3indicatorseebelowforvalues = col_character(),
                                    siteinfluence = col_character(),
                                    amenitiesseeamenities2field190 = col_character(),
                                    otherimprbuildingindicator1 = col_character(),
                                    otherimprbuildingindicator2 = col_character(),
                                    otherimprbuildingindicator3 = col_character(),
                                    otherimprbuildingindicator4 = col_character(),
                                    neighborhoodcode = col_character(),
                                    condoprojectbldgname = col_character(),
                                    otherimprbuildingindicator5 = col_character(),
                                    amenities2seefield182 = col_character(),
                                    otherimprbuildingarea1 = col_character(),
                                    otherimprbuildingarea2 = col_character(),
                                    otherimprbuildingarea3 = col_character(),
                                    otherimprbuildingarea4 = col_character(),
                                    otherimprbuildingarea5 = col_character(),
                                    otherrooms = col_character(),
                                    extrafeatures1area = col_character(),
                                    extrafeatures1indicator = col_character(),
                                    topography = col_character(),
                                    rooftype = col_character(),
                                    extrafeatures2area = col_character(),
                                    extrafeatures2indicator = col_character(),
                                    extrafeatures3area = col_character(),
                                    extrafeatures3indicator = col_character(),
                                    extrafeatures4area = col_character(),
                                    extrafeatures4indicator = col_character(),
                                    oldapn = col_character(),
                                    buildingcondition = col_character(),
                                    lotsizefrontagefeet = col_character(),
                                    lotsizedepthfeet = col_character(),
                                    commentssummaryofbuildingcardsdrrecords = col_character(),
                                    water = col_character(),
                                    sewer = col_character(),
                                    matchcodefromgeostan = col_character(),
                                    locationcodefromgeostan = col_character(),
                                    rawpropertyhousenumber = col_character(),
                                    rawpropertyhousealpha = col_character(),
                                    rawpropertystreetdirectionleft = col_character(),
                                    rawpropertystreetsuffix = col_character(),
                                    rawpropertystreetdirectionright = col_character(),
                                    rawpropertyunitnumber = col_character(),
                                    rawpropertycityname = col_character(),
                                    rawpropertystate = col_character(),
                                    rawpropertyzipcode = col_character(),
                                    rawpropertyzip4 = col_character(),
                                    rawmailinghousenumber = col_character(),
                                    rawmailinghousealpha = col_character(),
                                    rawmailingstreetdirectionleft = col_character(),
                                    rawmailingstreetname = col_character(),
                                    rawmailingstreetsuffix = col_character(),
                                    rawmailingstreetdirectionright = col_character(),
                                    rawmailingunitnumber = col_character(),
                                    rawmailingcityname = col_character(),
                                    rawmailingstate = col_character(),
                                    rawmailingzipcode = col_character(),
                                    rawmailingzip4 = col_character(),
                                    edition = col_character(),
                                    owner1firstname = col_character(),
                                    owner1middlename = col_character(),
                                    owner1lastname = col_character(),
                                    owner2firstname = col_character(),
                                    owner2middlename = col_character(),
                                    parsedownersourcecode = col_character()
                               ))
  
  
  # add county names
  county_names <- tibble(
    county_fips = as.character(c(11001, 24017, 24021, 24031, 24033, 
                                 51013, 51059, 51107, 51153, 51510, 
                                 51600, 51610, 51683, 51685)),
    county_name = c("District of Columbia", "Charles County",
                    "Frederick County", "Montgomery County",
                    "Prince George's County", "Arlington County",
                    "Fairfax County", "Loudoun County",
                    "Prince William County", "Alexandria city",
                    "Fairfax city", "Falls Church city",
                    "Manassas city", "Manassas Park city")
  )
  
  cog_assessment <- cog_assessment %>% 
    rename(county_fips = fipscodestatecounty) %>% 
    left_join(county_names, by = "county_fips") %>% 
    select(county_fips, county_name, everything())
  
  # add land use codes
  codes <- read_csv(
    "../Doc/assessment_landuse.csv",
    col_names = c("standardizedlandusecode", "codedescription"),
    col_types = cols(standardizedlandusecode = col_character(),
                     codedescription = col_character())
  )
  
  cog_assessment <- cog_assessment %>% 
    left_join(codes, by = "standardizedlandusecode")
  
  # return dataset  
  cog_assessment
}